# Generated by Django 5.1.5 on 2025-04-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_expense_mode_alter_expense_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Bank Transfer', 'Bank Transfer'), ('Mobile Payment', 'Mobile Payment')], default='Cash', max_length=100),
        ),
    ]
