# Generated by Django 5.1.5 on 2025-04-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_expense_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='mode',
        ),
        migrations.AddField(
            model_name='expense',
            name='paymentType',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Mobile', 'Mobile'), ('Bank', 'Bank')], default='Cash', max_length=100),
        ),
    ]
