# Generated by Django 5.1.5 on 2026-09-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_expensegroup_groupexpense_groupexpenseshare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='transaction_type',
            field=models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], default='DEBIT', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Entertainment', 'Entertainment'), ('Utilities', 'Utilities'), ('Shopping', 'Shopping'), ('Health', 'Health'), ('Rent', 'Rent'), ('Salary', 'Salary'), ('Freelance', 'Freelance'), ('Investment', 'Investment'), ('Refund', 'Refund'), ('Gift', 'Gift'), ('Other', 'Other')], max_length=100),
        ),
    ]
